version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=teste123
    ports:
      - 8082:8081
    extra_hosts:
        - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  simples-api:
    container_name: simples-api
    hostname: simples_api
    image: simples_api
    build:
      context: .
      dockerfile: ./apis/simples-api/Dockerfile.simples.api
      target: development
    depends_on:
      - redis
    environment:
      - REDIS_URL="redis://host.docker.internal:6379"
    ports:
      - 4001:4001
    # command: npm run start:dev
    env_file:
      - .env.dev
    links:
      - redis
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - monorepo_net

volumes:
  api_simples_vol:
  node_modules:
  postgres_data:
  redis_data:

networks:
  monorepo_net:
    driver: bridge
